# Generated by Django 4.2.2 on 2024-10-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='detalle',
            field=models.TextField(blank=True),
        ),
    ]
